DEBUG = True

USERNAME = 'root'
PASSWORD = '2013'
SERVER = 'localhost'
DB = 'escola'

SQLALCHEMY_DATABASE_URI = f'mysql+pymysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_NOTIFICATIONS = True